### ISSUE TITLE
Package spuriously supports Python 3.7

### ISSUE THREAD

**Issue by cpcloud** [conda-forge/impyla-feedstock#12]
This package is live on conda-forge and can be installed into an environment containing Python 3.7. However, this package does *not* support Python 3.7 because of https://github.com/cloudera/impyla/issues/312. There's a PR up to address it (https://github.com/cloudera/impyla/pull/309), but it's been lingering for awhile. In the meantime, this package should be taken down so that invalid Python 3.7 environments cannot be created.

**Comment by ZeroCool2u** [comment]
This can probably be closed, it looks like those issues in Impyla have been resolved.
